apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s_svc
  name: k8s_svc
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: k8s_svc
  type: NodePort
status:
  loadBalancer: {}
